/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGestorRouteImport } from './routes/_authenticated/gestor'
import { Route as AuthenticatedTecnicoRouteImport } from './routes/_authenticated/tecnico'
import { Route as AuthenticatedGestorIndexRouteImport } from './routes/_authenticated/gestor.index'
import { Route as AuthenticatedGestorCatalogoRouteImport } from './routes/_authenticated/gestor.catalogo'
import { Route as AuthenticatedGestorClientesRouteImport } from './routes/_authenticated/gestor.clientes'
import { Route as AuthenticatedGestorEquipeRouteImport } from './routes/_authenticated/gestor.equipe'
import { Route as AuthenticatedGestorRelatoriosRouteImport } from './routes/_authenticated/gestor.relatorios'
import { Route as AuthenticatedGestorRotasRouteImport } from './routes/_authenticated/gestor.rotas'
import { Route as AuthenticatedTecnicoIndexRouteImport } from './routes/_authenticated/tecnico.index'
import { Route as AuthenticatedTecnicoEquipamentosRouteImport } from './routes/_authenticated/tecnico.equipamentos'
import { Route as AuthenticatedTecnicoHistoricoRouteImport } from './routes/_authenticated/tecnico.historico'
import { Route as AuthenticatedTecnicoOsIdRouteImport } from './routes/_authenticated/tecnico.os.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestorRoute = AuthenticatedGestorRouteImport.update({
  id: '/gestor',
  path: '/gestor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTecnicoRoute = AuthenticatedTecnicoRouteImport.update({
  id: '/tecnico',
  path: '/tecnico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestorIndexRoute =
  AuthenticatedGestorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGestorRoute,
  } as any)
const AuthenticatedGestorCatalogoRoute =
  AuthenticatedGestorCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedGestorRoute,
  } as any)
const AuthenticatedGestorClientesRoute =
  AuthenticatedGestorClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedGestorRoute,
  } as any)
const AuthenticatedGestorEquipeRoute =
  AuthenticatedGestorEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedGestorRoute,
  } as any)
const AuthenticatedGestorRelatoriosRoute =
  AuthenticatedGestorRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedGestorRoute,
  } as any)
const AuthenticatedGestorRotasRoute =
  AuthenticatedGestorRotasRouteImport.update({
    id: '/rotas',
    path: '/rotas',
    getParentRoute: () => AuthenticatedGestorRoute,
  } as any)
const AuthenticatedTecnicoIndexRoute =
  AuthenticatedTecnicoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTecnicoRoute,
  } as any)
const AuthenticatedTecnicoEquipamentosRoute =
  AuthenticatedTecnicoEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedTecnicoRoute,
  } as any)
const AuthenticatedTecnicoHistoricoRoute =
  AuthenticatedTecnicoHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedTecnicoRoute,
  } as any)
const AuthenticatedTecnicoOsIdRoute =
  AuthenticatedTecnicoOsIdRouteImport.update({
    id: '/os/$id',
    path: '/os/$id',
    getParentRoute: () => AuthenticatedTecnicoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/gestor': typeof AuthenticatedGestorRouteWithChildren
  '/tecnico': typeof AuthenticatedTecnicoRouteWithChildren
  '/gestor/catalogo': typeof AuthenticatedGestorCatalogoRoute
  '/gestor/clientes': typeof AuthenticatedGestorClientesRoute
  '/gestor/equipe': typeof AuthenticatedGestorEquipeRoute
  '/gestor/relatorios': typeof AuthenticatedGestorRelatoriosRoute
  '/gestor/rotas': typeof AuthenticatedGestorRotasRoute
  '/tecnico/equipamentos': typeof AuthenticatedTecnicoEquipamentosRoute
  '/tecnico/historico': typeof AuthenticatedTecnicoHistoricoRoute
  '/gestor/': typeof AuthenticatedGestorIndexRoute
  '/tecnico/': typeof AuthenticatedTecnicoIndexRoute
  '/tecnico/os/$id': typeof AuthenticatedTecnicoOsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/gestor/catalogo': typeof AuthenticatedGestorCatalogoRoute
  '/gestor/clientes': typeof AuthenticatedGestorClientesRoute
  '/gestor/equipe': typeof AuthenticatedGestorEquipeRoute
  '/gestor/relatorios': typeof AuthenticatedGestorRelatoriosRoute
  '/gestor/rotas': typeof AuthenticatedGestorRotasRoute
  '/tecnico/equipamentos': typeof AuthenticatedTecnicoEquipamentosRoute
  '/tecnico/historico': typeof AuthenticatedTecnicoHistoricoRoute
  '/gestor': typeof AuthenticatedGestorIndexRoute
  '/tecnico': typeof AuthenticatedTecnicoIndexRoute
  '/tecnico/os/$id': typeof AuthenticatedTecnicoOsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/gestor': typeof AuthenticatedGestorRouteWithChildren
  '/_authenticated/tecnico': typeof AuthenticatedTecnicoRouteWithChildren
  '/_authenticated/gestor/catalogo': typeof AuthenticatedGestorCatalogoRoute
  '/_authenticated/gestor/clientes': typeof AuthenticatedGestorClientesRoute
  '/_authenticated/gestor/equipe': typeof AuthenticatedGestorEquipeRoute
  '/_authenticated/gestor/relatorios': typeof AuthenticatedGestorRelatoriosRoute
  '/_authenticated/gestor/rotas': typeof AuthenticatedGestorRotasRoute
  '/_authenticated/tecnico/equipamentos': typeof AuthenticatedTecnicoEquipamentosRoute
  '/_authenticated/tecnico/historico': typeof AuthenticatedTecnicoHistoricoRoute
  '/_authenticated/gestor/': typeof AuthenticatedGestorIndexRoute
  '/_authenticated/tecnico/': typeof AuthenticatedTecnicoIndexRoute
  '/_authenticated/tecnico/os/$id': typeof AuthenticatedTecnicoOsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/gestor'
    | '/tecnico'
    | '/gestor/catalogo'
    | '/gestor/clientes'
    | '/gestor/equipe'
    | '/gestor/relatorios'
    | '/gestor/rotas'
    | '/tecnico/equipamentos'
    | '/tecnico/historico'
    | '/gestor/'
    | '/tecnico/'
    | '/tecnico/os/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/gestor/catalogo'
    | '/gestor/clientes'
    | '/gestor/equipe'
    | '/gestor/relatorios'
    | '/gestor/rotas'
    | '/tecnico/equipamentos'
    | '/tecnico/historico'
    | '/gestor'
    | '/tecnico'
    | '/tecnico/os/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/gestor'
    | '/_authenticated/tecnico'
    | '/_authenticated/gestor/catalogo'
    | '/_authenticated/gestor/clientes'
    | '/_authenticated/gestor/equipe'
    | '/_authenticated/gestor/relatorios'
    | '/_authenticated/gestor/rotas'
    | '/_authenticated/tecnico/equipamentos'
    | '/_authenticated/tecnico/historico'
    | '/_authenticated/gestor/'
    | '/_authenticated/tecnico/'
    | '/_authenticated/tecnico/os/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestor': {
      id: '/_authenticated/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof AuthenticatedGestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tecnico': {
      id: '/_authenticated/tecnico'
      path: '/tecnico'
      fullPath: '/tecnico'
      preLoaderRoute: typeof AuthenticatedTecnicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestor/': {
      id: '/_authenticated/gestor/'
      path: '/'
      fullPath: '/gestor/'
      preLoaderRoute: typeof AuthenticatedGestorIndexRouteImport
      parentRoute: typeof AuthenticatedGestorRoute
    }
    '/_authenticated/gestor/catalogo': {
      id: '/_authenticated/gestor/catalogo'
      path: '/catalogo'
      fullPath: '/gestor/catalogo'
      preLoaderRoute: typeof AuthenticatedGestorCatalogoRouteImport
      parentRoute: typeof AuthenticatedGestorRoute
    }
    '/_authenticated/gestor/clientes': {
      id: '/_authenticated/gestor/clientes'
      path: '/clientes'
      fullPath: '/gestor/clientes'
      preLoaderRoute: typeof AuthenticatedGestorClientesRouteImport
      parentRoute: typeof AuthenticatedGestorRoute
    }
    '/_authenticated/gestor/equipe': {
      id: '/_authenticated/gestor/equipe'
      path: '/equipe'
      fullPath: '/gestor/equipe'
      preLoaderRoute: typeof AuthenticatedGestorEquipeRouteImport
      parentRoute: typeof AuthenticatedGestorRoute
    }
    '/_authenticated/gestor/relatorios': {
      id: '/_authenticated/gestor/relatorios'
      path: '/relatorios'
      fullPath: '/gestor/relatorios'
      preLoaderRoute: typeof AuthenticatedGestorRelatoriosRouteImport
      parentRoute: typeof AuthenticatedGestorRoute
    }
    '/_authenticated/gestor/rotas': {
      id: '/_authenticated/gestor/rotas'
      path: '/rotas'
      fullPath: '/gestor/rotas'
      preLoaderRoute: typeof AuthenticatedGestorRotasRouteImport
      parentRoute: typeof AuthenticatedGestorRoute
    }
    '/_authenticated/tecnico/': {
      id: '/_authenticated/tecnico/'
      path: '/'
      fullPath: '/tecnico/'
      preLoaderRoute: typeof AuthenticatedTecnicoIndexRouteImport
      parentRoute: typeof AuthenticatedTecnicoRoute
    }
    '/_authenticated/tecnico/equipamentos': {
      id: '/_authenticated/tecnico/equipamentos'
      path: '/equipamentos'
      fullPath: '/tecnico/equipamentos'
      preLoaderRoute: typeof AuthenticatedTecnicoEquipamentosRouteImport
      parentRoute: typeof AuthenticatedTecnicoRoute
    }
    '/_authenticated/tecnico/historico': {
      id: '/_authenticated/tecnico/historico'
      path: '/historico'
      fullPath: '/tecnico/historico'
      preLoaderRoute: typeof AuthenticatedTecnicoHistoricoRouteImport
      parentRoute: typeof AuthenticatedTecnicoRoute
    }
    '/_authenticated/tecnico/os/$id': {
      id: '/_authenticated/tecnico/os/$id'
      path: '/os/$id'
      fullPath: '/tecnico/os/$id'
      preLoaderRoute: typeof AuthenticatedTecnicoOsIdRouteImport
      parentRoute: typeof AuthenticatedTecnicoRoute
    }
  }
}

interface AuthenticatedGestorRouteChildren {
  AuthenticatedGestorCatalogoRoute: typeof AuthenticatedGestorCatalogoRoute
  AuthenticatedGestorClientesRoute: typeof AuthenticatedGestorClientesRoute
  AuthenticatedGestorEquipeRoute: typeof AuthenticatedGestorEquipeRoute
  AuthenticatedGestorRelatoriosRoute: typeof AuthenticatedGestorRelatoriosRoute
  AuthenticatedGestorRotasRoute: typeof AuthenticatedGestorRotasRoute
  AuthenticatedGestorIndexRoute: typeof AuthenticatedGestorIndexRoute
}

const AuthenticatedGestorRouteChildren: AuthenticatedGestorRouteChildren = {
  AuthenticatedGestorCatalogoRoute: AuthenticatedGestorCatalogoRoute,
  AuthenticatedGestorClientesRoute: AuthenticatedGestorClientesRoute,
  AuthenticatedGestorEquipeRoute: AuthenticatedGestorEquipeRoute,
  AuthenticatedGestorRelatoriosRoute: AuthenticatedGestorRelatoriosRoute,
  AuthenticatedGestorRotasRoute: AuthenticatedGestorRotasRoute,
  AuthenticatedGestorIndexRoute: AuthenticatedGestorIndexRoute,
}

const AuthenticatedGestorRouteWithChildren =
  AuthenticatedGestorRoute._addFileChildren(AuthenticatedGestorRouteChildren)

interface AuthenticatedTecnicoRouteChildren {
  AuthenticatedTecnicoEquipamentosRoute: typeof AuthenticatedTecnicoEquipamentosRoute
  AuthenticatedTecnicoHistoricoRoute: typeof AuthenticatedTecnicoHistoricoRoute
  AuthenticatedTecnicoIndexRoute: typeof AuthenticatedTecnicoIndexRoute
  AuthenticatedTecnicoOsIdRoute: typeof AuthenticatedTecnicoOsIdRoute
}

const AuthenticatedTecnicoRouteChildren: AuthenticatedTecnicoRouteChildren = {
  AuthenticatedTecnicoEquipamentosRoute: AuthenticatedTecnicoEquipamentosRoute,
  AuthenticatedTecnicoHistoricoRoute: AuthenticatedTecnicoHistoricoRoute,
  AuthenticatedTecnicoIndexRoute: AuthenticatedTecnicoIndexRoute,
  AuthenticatedTecnicoOsIdRoute: AuthenticatedTecnicoOsIdRoute,
}

const AuthenticatedTecnicoRouteWithChildren =
  AuthenticatedTecnicoRoute._addFileChildren(AuthenticatedTecnicoRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedGestorRoute: typeof AuthenticatedGestorRouteWithChildren
  AuthenticatedTecnicoRoute: typeof AuthenticatedTecnicoRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedGestorRoute: AuthenticatedGestorRouteWithChildren,
  AuthenticatedTecnicoRoute: AuthenticatedTecnicoRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
